name: "main"

on:
  pull_request:
  push:
  schedule:
    - cron: "0 7 * * 1"

env:
  extensions: "xml mbstring curl openssl dom xdebug"
  composer-install-args: "--no-progress --no-interaction --prefer-dist --no-scripts"

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
      fail-fast: false
    name: "Quality assurance"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args:  "${{ env.composer-install-args }}"
      - run: composer check:cs

  rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
      fail-fast: false
    name: "Rector"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args:  "${{ env.composer-install-args }}"
      - run: composer check:rector

  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
      fail-fast: false
    name: "Static analysis"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args: "${{ env.composer-install-args }}"

      - name: PHPStan Static Analysis
        run: composer check:phpstan

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
      fail-fast: false
    name: "Tests"

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args: "${{ env.composer-install-args }}"

      - name: PHPUnit
        run: composer test:phpunit